server:
  port: 8094  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: aigc-service
tj:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.tianji.aigc.controller
    title: 天机学堂 - AIGC接口文档
    description: 该服务包含AI接口先骨干功能
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
  auth:
    resource:
      enable: true
  jdbc:
    database: tj_aigc
  # 系统提示词
  ai:
    prompt:
      system:
        chat:
          data-id: system-chat-message # 系统提示词存储位置
          group: DEFAULT_GROUP
          timeout-ms: 20000
        # 路由智能体
        route-agent:
          data-id: route-agent-system-message.txt
        # 课程推荐智能体
        recommend-agent:
          data-id: recommend-agent-system-message.txt
        # 课程购买智能体
        buy-agent:
          data-id: buy-agent-system-message.txt
        # 课程咨询智能体
        consult-agent:
          data-id: consult-agent-system-message.txt

    #最大对话存储
    memory:
      max: 65536
      type: MySQL  # MySQL, Redis, MongoDB，目前只支持这三种实现，默认Redis